/FR_ROS_API_node:
  ros__parameters:
    AO_block: 1
    DO_block: 1
    DO_smooth: 0
    JOG_acc: 40
    JOG_maxdis: 5
    MoveC_blendR: 500.0
    MoveJLC_acc: 0.0
    MoveJLC_eaxis1: 0.0
    MoveJLC_eaxis2: 0.0
    MoveJLC_eaxis3: 0.0
    MoveJLC_eaxis4: 0.0
    MoveJLC_offset_flag: 0
    MoveJLC_offset_pos_rx: 0.0
    MoveJLC_offset_pos_ry: 0.0
    MoveJLC_offset_pos_rz: 0.0
    MoveJLC_offset_pos_x: 0.0
    MoveJLC_offset_pos_y: 0.0
    MoveJLC_offset_pos_z: 0.0
    MoveJLC_ovl: 100.0
    MoveJLC_tool: 0
    MoveJLC_user: 0
    MoveJ_blendT: 500.0
    MoveL_blendR: 500.0
    MoveL_search: 0.0
    NewSpline_blendR: 10.0
    Spline_acc: 0.0
    Spline_ovl: 100.0
    Spline_tool: 1
    Spline_user: 0
    collision_config: 1
    collision_mode: 0
    gripper_block: 1
    gripper_force: 50
    gripper_vel: 50
    gripper_maxtime: 30000
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    toolcoord_install: 0
    toolcoord_type: 0
    ServoJT_timeinterval: 0.008
    use_sim_time: false

